---
- hosts: localhost
  vars:
    INVENTORIES_DIRECTORY: "/exports/bastion/setup/ansible/inventory"
    GROUPS_DIRECTORY: "/exports/bastion/setup/ansible/groups"
    PLAYBOOK_DIRECTORY: "/exports/bastion/setup/code/playbooks"
    PLAYBOOK_ASSEMBLY_DIRECTORY: "{{ PLAYBOOK_DIRECTORY }}/inventory_assembly"
    PLAYBOOK_HOSTS_BLOCK: "{{ PLAYBOOK_ASSEMBLY_DIRECTORY }}/01.inventory.ini"
    PLAYBOOK_GROUP_BLOCK: "{{ PLAYBOOK_ASSEMBLY_DIRECTORY }}/03.inventory.ini"
    
    PLAYBOOK_INVENTORY: "{{ PLAYBOOK_DIRECTORY }}/inventory.ini"
  
  tasks:

  # Host definitions
  - name: update inventory to include all inventory lines from checked in servers
    # become: yes
    assemble:
      dest: "{{ PLAYBOOK_HOSTS_BLOCK }}"
      src: "{{ INVENTORIES_DIRECTORY }}"
  
  - name: update inventory to include all inventory groups from checked in servers
    # become: yes
    assemble:
      dest: "{{ PLAYBOOK_GROUP_BLOCK }}"
      src: "{{ GROUPS_DIRECTORY }}"
      
  - name: merge all inventory pieces to make final inventory file
    # become: yes
    assemble:
      dest: "{{ PLAYBOOK_INVENTORY }}"
      src: "{{ PLAYBOOK_ASSEMBLY_DIRECTORY }}"

